name: Bug report
description: Report a reproducible defect
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include exact steps and sample files if relevant.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: App version
      placeholder: e.g. 0.1.0
  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - Windows
        - macOS
        - Linux
        - Other
  - type: input
    id: node_version
    attributes:
      label: Node.js version
      placeholder: e.g. 20.18.0
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant logs/error text.
